name: MiniBlocks
main: com.caved_in.miniblocks.MiniBlocks
version: 1.0
description: Blocks, but minified
author: Brandon
depend: [Tunnels-Common, PopupMenuAPI]
commands:
   miniwand:
      usage: /<command>
      description: Used to get the mini-block wand
      aliases: [mw, mbw, mbwnd]
   miniblocks:
      usage: /<command> [SubCommand]
      description: Used to open the menu for selecting mini-blocks
      aliases: [mb, minblk, mbl, mbk]